language: csharp
mono: none
dotnet: 2.1.609
solution: DvelopSdk.sln
script:
- dotnet restore
- bash travis/deploy.sh
env:
  global:
  - secure: dYBzKU0V+toqgPTeqfLdxjqgsiwX/oEXs/EfNfCH831dS/B1/63pR9p3drVE2r+Bj3GBCGZeIWsSLAAT8mDLGY5snqNQ84v3/F3naDYfFzrr2NPVMIxpdZ3Kbk3i069mOxa0Ra42BoVgighhhFTAJQdnNGE/nlkHuxHf1iBlUwlBrl0dNR85Dfv2HNi/mB+6ZwBTJlVa5f9paEvozfgu9/sSkM8rP8CpptOGPQbqZdCbR6Ntu5Zf29CPwYuyCT00BgNbrk2A1PIjaABUPNN75NxAz3yI4EJbBLGFnjewJ1IWCbtCQQoHkSTaHbQl+cuxo39oJ4uDFA57VuplRpwnvLSKISewqSLs1Fi+RBjuj1qGu82wPrvoi6IQBEQLVqTVex2R/nJ+ezuHkrkpY/k/4X8pEfHYAenmf9iUC8eGeCxsQny2MHSli0UveRpq1l+bYkvAbsee8IcuAh1lzPMenFtt1xHWr3SPL55hay2GZab+MburCH7Xb2NzLsxADplyJbMr8D1MWQxSnAvIMFJcOb1dSjZW43b8ERmGMaz9Itc4nVAJTF3tblgE4uc6VpY+iWVWTqsBcDJ1Jp2gUMdmaMhI3yugG5mCwodIZyqeP1fr5Huq8FNmBVfWLo+gs5LIM0q67SZ11GmPEJq6r4zOEaA4BYNoR33qyRusxrI61IM=
